Repository TeamVastsea/QwQUI, pull requests merged in 2024-10, with the labels that each got.

#10 doc: featured readme doc
  README.md
Labels: documentation

#12 fix: ripple overflow
  packages/components/ripple/src/use-ripple.ts
Labels: bug

#14 doc: add social media img to readme
  README.md
Labels: documentation

#13 doc: improve doc
  doc/docs/_meta.json
  doc/docs/components/_meta.json
  doc/docs/components/animation/_meta.json
  doc/docs/components/animation/ripple.mdx
  doc/docs/index.md
  doc/docs/public/Logo.svg
  doc/docs/public/logo-with-text-dark.png
  doc/docs/public/logo-with-text-light.png
  doc/docs/public/rspress-dark-logo.png
  doc/docs/public/rspress-icon.png
  doc/docs/public/rspress-light-logo.png
  doc/rspress.config.ts
  packages/components/button/src/button.tsx
Labels: documentation

#32 feat: stack component
  .changeset/olive-pugs-accept.md
  doc/docs/components/_meta.json
  doc/docs/components/layout/_meta.json
  doc/docs/components/layout/stack.mdx
  doc/docs/components/layout/stack/basic-usage.tsx
  doc/docs/components/layout/stack/btn-style.scss
  packages/components/index.ts
  packages/components/stack/README.md
  packages/components/stack/__test__/stack.test.tsx
  packages/components/stack/index.ts
  packages/components/stack/package.json
  packages/components/stack/rslib.config.ts
  packages/components/stack/src/stack.module.scss
  packages/components/stack/src/stack.tsx
  packages/components/stack/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement

#35 feat(layout): group component
  .changeset/big-countries-punch.md
  doc/docs/components/layout/_meta.json
  doc/docs/components/layout/group.mdx
  doc/docs/components/layout/group/basic-usage.tsx
  doc/docs/components/layout/group/style.scss
  packages/components/group/README.md
  packages/components/group/__test__/group.test.tsx
  packages/components/group/index.ts
  packages/components/group/package.json
  packages/components/group/rslib.config.ts
  packages/components/group/src/group.module.scss
  packages/components/group/src/group.tsx
  packages/components/group/tsconfig.json
  packages/components/index.ts
  pnpm-lock.yaml
Labels: enhancement
